### ISSUE TITLE
Join click Meeting is not started continues loading show

### ISSUE THREAD

**Issue by harshal111** [Azure-Samples/communication-services-android-calling-hero#131]
I run this demo in my Android Platform and add Team meeting URL in Team Meeting option and Add Display Name click on Next button .

After that Click on Join Call button in Next screen and Loader showing continuously nothing happened and after sometime loader app is crashing 

When  i click on Sign IN button at first screen  Nothing Happened

**Comment by ShaunaSong** [comment]
Hey @harshal111 
Thanks for bringing it up, we are working on it. Will be back to you later.

**Comment by Mohtasim** [comment]
Hi @harshal111, did you put the "communicationTokenFetchUrl" in the "appSettings.properties" file? 
Please follow this [guide](https://learn.microsoft.com/en-ca/azure/communication-services/tutorials/trusted-service-tutorial) to get the URL.

**Comment by darshanpopat80802** [comment]
Hello @Mohtasim - I have key with me, but when I place key in value for "communicationTokenFetchUrl". My project will not run. It says some rules are not followed.

**Comment by kostyabakay** [comment]
Hi @Mohtasim. For the `communicationTokenFetchUrl` I put a value from `Azure Portal -> Settings -> Keys -> Endpoint` but it doesn't work. I see infinite `Joining call...`. Am I doing something wrong?
I tried both formats for endpoints:
`https://my-custom-resource.communication.azure.com/`
`my-custom-resource.communication.azure.com/`
