### ISSUE TITLE
Securing the azure function results in a 401 on Android only

### ISSUE THREAD

**Issue by mihai1voicescu** [Azure-Samples/communication-services-android-calling-hero#134]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Complete the tutorial including https://github.com/Azure-Samples/communication-services-android-calling-hero#securing-authentication-endpoint

### Any log messages given by the failure
```
2023-11-01 14:54:47.189 10874-10896 Volley                  com...samples.communication.calling  E  [68] NetworkUtility.shouldRetryException: Unexpected response code 401 for https://XXXXXXXXX.azurewebsites.net/api/Function
2023-11-01 14:54:47.266 10874-10896 Volley                  com...samples.communication.calling  E  [68] NetworkUtility.shouldRetryException: Unexpected response code 401 for https://XXXXXXXXX.azurewebsites.net/api/Function
2023-11-01 14:54:47.266 10874-10874 TokenService            com...samples.communication.calling  E  Failed getting communication token
                                                                                                    com.android.volley.AuthFailureError
                                                                                                    	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:189)
                                                                                                    	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
                                                                                                    	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
                                                                                                    	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
                                                                                                    	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

### Expected/desired behavior
I expected the login to work and the Function App to be called.

### OS and Version?
Android Pixel 6 Pro Emulator with API 33

### Versions
master

### Mention any other details that might be useful
We think we followed the details of the tutorial correctly.

As soon as we enable the authentication the Authentication Function App does not work anymore and returns a 401 Unauthorized.
We tried adding the `App registration` of the Identity provider on the Function App both on the Function App and on the Android App but nothing seems to work.

The funny thing is that if we try the function endpoint from the browser it works...

I added some screenshots maybe there is something we are missing.

Authentication App function screenshots:
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/11346489/7c022417-b2c7-487b-85cd-1123a8ebd817)
![Screenshot 2023-11-01 at 15 06 07](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/11346489/27ea4a7a-28c7-46fb-a1cf-f4f3deab7b65)

App function identity provider:
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/11346489/0ad82c96-271a-4bce-94ad-f9a08f8295f7)

Android App function screenshots:
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/11346489/5265a783-d075-4a4b-890e-99ff5bbeb086)
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/11346489/df55b3be-98a0-4f24-955c-dea104e109a7)
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/11346489/c083634e-efd0-4407-9bd4-fcc0a5d46ea9)
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/11346489/060d64f6-79b1-4eba-b3c2-821eca9596b4)

**Comment by iaulakh** [comment]
Hi @mihai1voicescu,

Thank you for raising the issue. To follow up, would it be possible to obtain the following information:

1) If AAD is disabled, does the 'call join with token' function work fine?
2) After enabling AAD, have you followed all the steps for setting up 'MSAL Android configuration,' 'AndroidManifest.xml,' and setting 'android:path'?
3) Are you using an organization tenant, or is this specific to a particular project?

Thank you.

**Comment by oleksandr-hulak** [comment]
Hi @iaulakh,

I am @mihai1voicescu's colleague, and can reply to the questions above.

> 1. If AAD is disabled, does the 'call join with token' function work fine?

- What is meant by `call join with token` function, when we don't have an AAD auth token? When I disable AAD, navigate to "Join a call" -> "Teams Meeting" -> Enter a meeting link and my display name -> Join call -> The `CallComposite` gets stuck at "Joining a call...". But I am assuming, you are asking about something different.

> 2. After enabling AAD, have you followed all the steps for setting up 'MSAL Android configuration,' 'AndroidManifest.xml,' and setting 'android:path'?

- Yes:
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/10137373/6c00a0f8-ed68-4c2e-8a83-f1e0f08a5440)
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/10137373/de82e672-5db1-450d-a67b-3375ec1590c8)
![image](https://github.com/Azure-Samples/communication-services-android-calling-hero/assets/10137373/caf44c66-f9f5-4ea2-b314-79dbfa61ddc3)

> 3. Are you using an organization tenant, or is this specific to a particular project?

- We use a "common" tenant, which is multi-tenant, see the screenshot above. The user work account we're logging into has a Microsoft 365 subscription.

**Comment by iaulakh** [comment]
Hi @oleksandr-hulak,

Re 1): `The CallComposite gets stuck at "Joining a call..."` This issue occurs when AAD is enabled on Azure Function. For testing purposes, you can temporarily disable AAD on Azure Function and paste the function URL into your browser to confirm that the token is received with no authentication, allowing you to test joining the call.

Re 2) and 3): It seems that the configurations may not be set correctly. Would it be possible for you to create a sample project following the steps below in a sample Android project to ensure that AAD works?

[Register your app under Azure Active Directory (using Android platform settings)](https://docs.microsoft.com/azure/active-directory/develop/tutorial-v2-android)
[Configure your App Service or Azure Functions app to use Azure AD login](https://docs.microsoft.com/azure/app-service/configure-authentication-provider-aad)

**Comment by oleksandr-hulak** [comment]
Hi @iaulakh.
The issue was related to the version of the acquired Bearer Token. 

I noticed that somehow the ID token of the received `IAccount` instance passes the Azure Function authentication, while the Auth Bearer token doesn't. [https://jwt.ms](https://jwt.ms/) helped to take a look inside these ID and Auth tokens, and they had different issuers - `https://login.microsoftonline.com/<tenant_id>/v2.0` and `https://sts.windows.net/<tenant_id>` accordingly. That's because the ID token is of version 2, and the Auth token is of version 1.

MSAL ignored the set `"accessTokenAcceptedVersion": 2` in the Azure AD Application Manifest. It turned out that the requested token scopes affect the resulting token version - as I requested _"aadScopes=User.Read, People.Read, Chat.ReadBasic"_, MSAL returned a v1 token specifically for Graph API.

In order to make it work, I had to expose an API in my AD Application, with a custom **"user_impersonation"** scope. Requesting scopes for both Graph API + **"user_impersonation"** doesn't work, so I request it separately with a single `api://<client_id>/user_impersonation` scope.

And now the token returned by MSAL with "user_impersonation" is of version 2, which makes it have a correct issuer `https://login.microsoftonline.com/<tenant_id>/v2.0`, passing the Azure AD Function Microsoft Identity provider authentication.

**Comment by iaulakh** [comment]
Thanks for the update, @oleksandr-hulak. Can we go ahead and close this issue? Feel free to open a new one if needed.

**Comment by oleksandr-hulak** [comment]
> Thanks for the update, @oleksandr-hulak. Can we go ahead and close this issue? Feel free to open a new one if needed.

Yes, feel free to close the issue.
