### ISSUE TITLE
Trusted Service with Azure Functions link in readme.md not found

### ISSUE THREAD

**Issue by hyounoo** [Azure-Samples/communication-services-android-calling-hero#14]
> Please provide us with the following information:
Trusted Service with Azure Functions link not working
https://github.com/Azure-Samples/communication-services-android-calling-hero/tutorials/trusted-service-tutorial.md

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Click Trusted Service with Azure Functions link and see not found error.

### Any log messages given by the failure
> Attaching screenshot
![image](https://user-images.githubusercontent.com/9585318/113468383-cb273080-9480-11eb-8dc1-3afb42992249.png)

### Expected/desired behavior
> Expect to see the document.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win10

### Versions
> 2004

### Mention any other details that might be useful
Just want to see the document to follow the instruction.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by waynemo** [comment]
Thanks for the feedback @hyounoo.

The link in the README will fixed soon. But in the mean time, here is the correct link:
https://docs.microsoft.com/azure/communication-services/tutorials/trusted-service-tutorial

**Comment by waynemo** [comment]
The README has been updated with the correct link. Closing.
