### ISSUE TITLE
App crashes if receiver not ready- Android

### ISSUE THREAD

**Issue by mohdshafnaz** [Azure-Samples/communication-services-android-calling-hero#81]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

If the receiver side not initialized the incoming call listener , App crashes from the calling side after 3-4 seconds.
>

### Any log messages given by the failure

>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by iaulakh** [comment]
@mohdshafnaz we appreciate the feedback. To help look into the issue further could you please provide some additional information?

- The specific commit used to run the app.
- Detailed steps to reproduce the issue. Screenshots and/or screen recordings would be helpful as well.
  - please elaborate receiver side? It will be great if you can share steps to setup receiver side.
  - calling side refers to  Android calling sample application?
  - please attach crash logs from Android Studio.
- Type of devices and Android versions.

Thanks.

**Comment by mohdshafnaz** [comment]
When I start call , if the receiver side is not active app getting crashed and 
"**The event handler cannot be null**" error is showing,
the snippet code is below.

```
 private void onParticipantsUpdated(final ParticipantsUpdatedEvent participantsUpdatedEvent) {
        boolean doUpdate = false;
        if (participantsUpdatedEvent != null && participantsUpdatedEvent.getRemovedParticipants() != null && !participantsUpdatedEvent.getRemovedParticipants().isEmpty()) {
            doUpdate |= removeParticipants(participantsUpdatedEvent.getRemovedParticipants());
        }
        if (participantsUpdatedEvent != null && participantsUpdatedEvent.getAddedParticipants() != null && !participantsUpdatedEvent.getAddedParticipants().isEmpty()) {
            doUpdate |= addParticipants(participantsUpdatedEvent.getAddedParticipants());
        }
        if (doUpdate) {
            displayedParticipantsLiveData.postValue(displayedRemoteParticipants);
        }
    }


 private boolean removeParticipants(final List<RemoteParticipant> removedParticipants) {
        boolean isDisplayedRemoteParticipantsChanged = false;
        for (final RemoteParticipant removedParticipant : removedParticipants) {
            final String removedParticipantId = getId(removedParticipant);

            unbindOnVideoStreamsUpdatedListener(removedParticipant);
            unbindOnIsMutedChangedListener(removedParticipant);
           unbindOnIsSpeakingChangedListener(removedParticipant);
            unbindOnParticipantStateChangedListener(removedParticipant);
.......
.
.
.
    private void unbindOnIsMutedChangedListener(final RemoteParticipant remoteParticipant) {
        if (remoteParticipant != null && getId(remoteParticipant) != null) {
            final String removedParticipantId = getId(remoteParticipant);
            if (removedParticipantId != null && mutedChangedListenersMap != null) {
                remoteParticipant.removeOnIsMutedChangedListener(mutedChangedListenersMap.remove(removedParticipantId));
            }
        }
    }

```


Crashes are showing on 

   **remoteParticipant.removeOnIsMutedChangedListener(mutedChangedListenersMap.remove(removedParticipantId));**
inside **unbindOnIsMutedChangedListener**()

Is there anything I might missed on implementation

**Comment by iaulakh** [comment]
@mohdshafnaz thank you for providing more information. could you please provide some additional details to identify root cause of issue?

1) are you keeping cache of remote participants `Map<String, RemoteParticipant> remoteParticipantsMap` as indicated in file `com/azure/samples/communication/calling/external/calling/CallingContext.java`?
2) could you please share complete exception details with stack trace? 
3) are you able to reproduce issue in sample application `https://github.com/Azure-Samples/communication-services-android-calling-hero`? 
4) could you share your implementation code file to identify issue?

As I do not have complete details to analyze issue. Looking at `The event handler cannot be null` can be caused by calling 'removeOnIsMutedChangedListener' with null value. 

The workaround can be below but it is not appropriate. The proper fix will be to figure out why `mutedChangedListenersMap` has no `PropertyChangedListener` as `bindOnIsMutedChangedListener` should be called before `unbindOnIsMutedChangedListener`

```java
      final PropertyChangedListener propertyChangedListener = mutedChangedListenersMap.remove(removedParticipantId);
        if(propertyChangedListener != null) {
            remoteParticipant.removeOnIsMutedChangedListener(null);
        }
```

**Comment by mohdshafnaz** [comment]
Thanks for your reply. 


Yes. I am keeping cache of remote participants Map variable .
and also I am keeping caching for following values same as in android-calling-hero.

`    private final Map<String, RemoteParticipant> remoteParticipantsMap;
    private final List<RemoteParticipant> displayedRemoteParticipants;
    private final MutableLiveData<List<RemoteParticipant>> displayedParticipantsLiveData;
    private final Set<String> displayedRemoteParticipantIds;

    private final Map<String, RemoteVideoStreamsUpdatedListener> videoStreamsUpdatedListenersMap;
    private final Map<String, PropertyChangedListener> mutedChangedListenersMap;
    private final Map<String, PropertyChangedListener> isSpeakingChangedListenerMap;
    private final Map<String, PropertyChangedListener> participantStateChangedListenerMap;`
    
    by using your tip with a small changes, I could handle the crash issue. 
code is below. I guess I have handled the issue. 


`   final PropertyChangedListener propertyChangedListener = mutedChangedListenersMap.remove(removedParticipantId);
        if(propertyChangedListener != null) {
            remoteParticipant.removeOnIsMutedChangedListener(propertyChangedListener);
        }
else{
  remoteParticipant.removeOnIsMutedChangedListener(null);
}
`

Thank you.

**Comment by iaulakh** [comment]
Hi @mohdshafnaz, `remoteParticipant.removeOnIsMutedChangedListener(null);` is not required.

```java
final PropertyChangedListener propertyChangedListener = mutedChangedListenersMap.remove(removedParticipantId); 
if(propertyChangedListener != null) { 
       remoteParticipant.removeOnIsMutedChangedListener(propertyChangedListener); 
} 
//else can be removed
else { 
      remoteParticipant.removeOnIsMutedChangedListener(null); 
}
```

The proper fix will be to figure out why `mutedChangedListenersMap` has no `PropertyChangedListener` as `bindOnIsMutedChangedListener` should be called before `unbindOnIsMutedChangedListener`.
