### ISSUE TITLE
Handle Incoming Calls when app is not active

### ISSUE THREAD

**Issue by mohdshafnaz** [Azure-Samples/communication-services-android-calling-hero#83]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

I would like to need to clarify on incoming call side.
If the app is in foreground we can use IncomingCallListener for trigger if the callAgent is active.
But if the app is not in foreground/active then I had to implement FCM services like following code from the tutorial.  

`try {
    IncomingCallInformation notification = IncomingCallInformation.fromMap(pushNotificationMessageDataFromFCM);
    Future handlePushNotificationFuture = callAgent.handlePushNotification(notification).get();
}
catch(Exception e) {
    System.out.println("Something went wrong while handling the Incoming Calls Push Notifications.");
}`

After getting incoming call details from FCM ,I need to start incoming call screen with an accept and reject button.
For this purpose need to know the structure of payload to trigger callAgent. 

- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
When a user calls the receiver side must get the push notification with expected data. Receiver side can establish a connection and get the details of Incoming call details. 
>

### OS and Version?
> macOS 11(BigSur)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kagbakpem** [comment]
@mohdshafnaz], the snippet is slightly wrong. Please use this instead: 
```java
    try {
        PushNotificationInfo notification = PushNotificationInfo.fromMap(pushNotificationMessageDataFromFCM);
        // showNotificationForIncomingCall(notification);
        // The notification object from PushNotificationInfo contain all the necessary fields (From, To, DisplayName, etc.) to display the incoming call. See [here](https://docs.microsoft.com/en-us/java/api/com.azure.android.communication.calling.pushnotificationinfo?view=communication-services-java-android)

        // Call the API below to handle the Push notification payload. Once this is called and had succeeded, the incoming call should be handled as usual, ie: registering an `OnIncomingCall` event handler on CallAgent as you'll do normally when the app is in foreground.
        callAgent.handlePushNotification(notification).get();
    } catch(Exception e) {
        System.out.println("Something went wrong while handling the Incoming Calls Push Notifications.");
    }
```

Hopefully, this helps. If you have further question, do not hesitate to contact us.

**Comment by mohdshafnaz** [comment]
@kagbakpem 

`
           val notification =   PushNotificationInfo.fromMap(pushNotificationMessageDataFromFCM)
           callAgent.handlePushNotification(notification).get()
`

This line of code does not make any impact, and the line of codes coming after this does not get executed. 
No error is showing as well. 
Would like know how the **handlePushNotification()** handles the incoming call?

**Comment by kagbakpem** [comment]
@mohdshafnaz, apologies, i didn't post the content to handle the incoming call as i was under the impression you had the logic to handle this when the app is in Foreground. The logic would be the same.
Here is a link to a [Quickstart ](https://github.com/Azure-Samples/communication-services-android-quickstarts/blob/3ad5a5c4cf3a6d2e89afbd99ea46352202d54864/videoCallingQuickstart/app/src/main/java/com/example/videocallingquickstart/MainActivity.java#L108) sample that describe how to handle an incoming call flow by adding an OnIncomingCallListener to a CallAgent object.
Give it a try and let us know if this helps.

**Comment by mohdshafnaz** [comment]
@kagbakpem Sorry for being minimal explanation from my side. I already implemented the incoming call handling If the app is in foreground without using the piece of code what you have sent on previous comment. I used only FCM push. 

I clearly understand what you are trying to say. Thank you for the time. It helped.
